/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class CreateInterestRequestBuilder {
    //the instance to build
    private CreateInterestRequest createInterestRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateInterestRequestBuilder() {
        createInterestRequest = new CreateInterestRequest();
    }

    /**
     * Days
     */
    public CreateInterestRequestBuilder days(int days) {
        createInterestRequest.setDays(days);
        return this;
    }

    /**
     * Type
     */
    public CreateInterestRequestBuilder type(String type) {
        createInterestRequest.setType(type);
        return this;
    }

    /**
     * Amount
     */
    public CreateInterestRequestBuilder amount(int amount) {
        createInterestRequest.setAmount(amount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateInterestRequest build() {
        return createInterestRequest;
    }
}