/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class CreateSubscriptionSplitRequestBuilder {
    //the instance to build
    private CreateSubscriptionSplitRequest createSubscriptionSplitRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateSubscriptionSplitRequestBuilder() {
        createSubscriptionSplitRequest = new CreateSubscriptionSplitRequest();
    }

    /**
     * Defines if the split is enabled
     */
    public CreateSubscriptionSplitRequestBuilder enabled(boolean enabled) {
        createSubscriptionSplitRequest.setEnabled(enabled);
        return this;
    }

    /**
     * Split
     */
    public CreateSubscriptionSplitRequestBuilder rules(List<CreateSplitRequest> rules) {
        createSubscriptionSplitRequest.setRules(rules);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateSubscriptionSplitRequest build() {
        return createSubscriptionSplitRequest;
    }
}