/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class CreateCardPaymentContactlessRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = -1739099960915993977L;
    private String type;
    private CreateApplePayRequest applePay;
    private CreateGooglePayRequest googlePay;
    private CreateEmvDecryptRequest emv;
    /** GETTER
     * The authentication type
     */
    @JsonGetter("type")
    public String getType ( ) { 
        return this.type;
    }
    
    /** SETTER
     * The authentication type
     */
    @JsonSetter("type")
    public void setType (String value) { 
        this.type = value;
    }
 
    /** GETTER
     * The ApplePay Token Payment Request
     */
    @JsonGetter("apple_pay")
    public CreateApplePayRequest getApplePay ( ) { 
        return this.applePay;
    }
    
    /** SETTER
     * The ApplePay Token Payment Request
     */
    @JsonSetter("apple_pay")
    public void setApplePay (CreateApplePayRequest value) { 
        this.applePay = value;
    }
 
    /** GETTER
     * The GooglePay Token Payment Request
     */
    @JsonGetter("google_pay")
    public CreateGooglePayRequest getGooglePay ( ) { 
        return this.googlePay;
    }
    
    /** SETTER
     * The GooglePay Token Payment Request
     */
    @JsonSetter("google_pay")
    public void setGooglePay (CreateGooglePayRequest value) { 
        this.googlePay = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("emv")
    public CreateEmvDecryptRequest getEmv ( ) { 
        return this.emv;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("emv")
    public void setEmv (CreateEmvDecryptRequest value) { 
        this.emv = value;
    }
 
}
