/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class CreateFineRequestBuilder {
    //the instance to build
    private CreateFineRequest createFineRequest;

    /**
     * Default constructor to initialize the instance
     */
    public CreateFineRequestBuilder() {
        createFineRequest = new CreateFineRequest();
    }

    /**
     * Days
     */
    public CreateFineRequestBuilder days(int days) {
        createFineRequest.setDays(days);
        return this;
    }

    /**
     * Type
     */
    public CreateFineRequestBuilder type(String type) {
        createFineRequest.setType(type);
        return this;
    }

    /**
     * Amount
     */
    public CreateFineRequestBuilder amount(int amount) {
        createFineRequest.setAmount(amount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CreateFineRequest build() {
        return createFineRequest;
    }
}