/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class GetFineResponseBuilder {
    //the instance to build
    private GetFineResponse getFineResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetFineResponseBuilder() {
        getFineResponse = new GetFineResponse();
    }

    /**
     * Days
     */
    public GetFineResponseBuilder days(int days) {
        getFineResponse.setDays(days);
        return this;
    }

    /**
     * Type
     */
    public GetFineResponseBuilder type(String type) {
        getFineResponse.setType(type);
        return this;
    }

    /**
     * Amount
     */
    public GetFineResponseBuilder amount(int amount) {
        getFineResponse.setAmount(amount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetFineResponse build() {
        return getFineResponse;
    }
}