/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class GetInterestResponseBuilder {
    //the instance to build
    private GetInterestResponse getInterestResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetInterestResponseBuilder() {
        getInterestResponse = new GetInterestResponse();
    }

    /**
     * Days
     */
    public GetInterestResponseBuilder days(int days) {
        getInterestResponse.setDays(days);
        return this;
    }

    /**
     * Type
     */
    public GetInterestResponseBuilder type(String type) {
        getInterestResponse.setType(type);
        return this;
    }

    /**
     * Amount
     */
    public GetInterestResponseBuilder amount(int amount) {
        getInterestResponse.setAmount(amount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetInterestResponse build() {
        return getInterestResponse;
    }
}