/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class GetPixPayerResponseBuilder {
    //the instance to build
    private GetPixPayerResponse getPixPayerResponse;

    /**
     * Default constructor to initialize the instance
     */
    public GetPixPayerResponseBuilder() {
        getPixPayerResponse = new GetPixPayerResponse();
    }

    public GetPixPayerResponseBuilder name(String name) {
        getPixPayerResponse.setName(name);
        return this;
    }

    public GetPixPayerResponseBuilder document(String document) {
        getPixPayerResponse.setDocument(document);
        return this;
    }

    public GetPixPayerResponseBuilder documentType(String documentType) {
        getPixPayerResponse.setDocumentType(documentType);
        return this;
    }

    public GetPixPayerResponseBuilder bankAccount(GetPixBankAccountResponse bankAccount) {
        getPixPayerResponse.setBankAccount(bankAccount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public GetPixPayerResponse build() {
        return getPixPayerResponse;
    }
}