/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class GetSubscriptionSplitResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 6654819743020101604L;
    private boolean enable;
    private GetSplitResponse rules;
    /** GETTER
     * Defines if the split is enabled
     */
    @JsonGetter("enable")
    public boolean getEnable ( ) { 
        return this.enable;
    }
    
    /** SETTER
     * Defines if the split is enabled
     */
    @JsonSetter("enable")
    public void setEnable (boolean value) { 
        this.enable = value;
    }
 
    /** GETTER
     * Split
     */
    @JsonGetter("rules")
    public GetSplitResponse getRules ( ) { 
        return this.rules;
    }
    
    /** SETTER
     * Split
     */
    @JsonSetter("rules")
    public void setRules (GetSplitResponse value) { 
        this.rules = value;
    }
 
}
