/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;

public class ListAnticipationResponseBuilder {
    //the instance to build
    private ListAnticipationResponse listAnticipationResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ListAnticipationResponseBuilder() {
        listAnticipationResponse = new ListAnticipationResponse();
    }

    /**
     * Anticipations
     */
    public ListAnticipationResponseBuilder data(List<GetAnticipationResponse> data) {
        listAnticipationResponse.setData(data);
        return this;
    }

    /**
     * Object used for returning lists of objects with pagination
     */
    public ListAnticipationResponseBuilder paging(PagingResponse paging) {
        listAnticipationResponse.setPaging(paging);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ListAnticipationResponse build() {
        return listAnticipationResponse;
    }
}