/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.ALWAYS)
public class UpdateSubscriptionSplitRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 9121333260058276680L;
    private boolean enabled;
    private List<CreateSplitRequest> rules;
    /** GETTER
     * Defines if the split is enabled
     */
    @JsonGetter("enabled")
    public boolean getEnabled ( ) { 
        return this.enabled;
    }
    
    /** SETTER
     * Defines if the split is enabled
     */
    @JsonSetter("enabled")
    public void setEnabled (boolean value) { 
        this.enabled = value;
    }
 
    /** GETTER
     * Split
     */
    @JsonGetter("rules")
    public List<CreateSplitRequest> getRules ( ) { 
        return this.rules;
    }
    
    /** SETTER
     * Split
     */
    @JsonSetter("rules")
    public void setRules (List<CreateSplitRequest> value) { 
        this.rules = value;
    }
 
}
