/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.controllers;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import me.pagar.api.models.*;
import me.pagar.api.exceptions.*;
import me.pagar.api.APIHelper;
import me.pagar.api.DateTimeHelper;
import me.pagar.api.Configuration;
import me.pagar.api.testing.TestHelper;
import me.pagar.api.controllers.InvoicesController;

import com.fasterxml.jackson.core.type.TypeReference;
import org.joda.time.DateTime;
import org.joda.time.LocalDate;

public class InvoicesControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static InvoicesController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getInvoices();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * Gets all invoices
     * @throws Throwable
     */
    @Test
    public void testTestGetInvoices() throws Throwable {
        // Parameters for the API call
        Integer page = null;
        Integer size = null;
        String code = null;
        String customerId = null;
        String subscriptionId = null;
        DateTime createdSince = null;
        DateTime createdUntil = null;
        String status = null;
        DateTime dueSince = null;
        DateTime dueUntil = null;
        String customerDocument = null;

        // Set callback and perform API call
        ListInvoicesResponse result = null;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.getInvoices(page, size, code, customerId, subscriptionId, createdSince, createdUntil, status, dueSince, dueUntil, customerDocument);
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders(), true));

    }

}
