/*
 * PagarmeCoreApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package me.pagar.api.controllers;

import static org.junit.Assert.*;

import java.io.*;
import java.util.*;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;

import me.pagar.api.models.*;
import me.pagar.api.exceptions.*;
import me.pagar.api.APIHelper;
import me.pagar.api.DateTimeHelper;
import me.pagar.api.Configuration;
import me.pagar.api.testing.TestHelper;
import me.pagar.api.controllers.TransfersController;

import com.fasterxml.jackson.core.type.TypeReference;
import org.joda.time.DateTime;
import org.joda.time.LocalDate;

public class TransfersControllerTest extends ControllerTestBase {
    
    /**
     * Controller instance (for all tests)
     */
    private static TransfersController controller;
    
    /**
     * Setup test class
     */
    @BeforeClass
    public static void setUpClass() {
        controller = getClient().getTransfers();
    }

    /**
     * Tear down test class
     * @throws IOException
     */
    @AfterClass
    public static void tearDownClass() throws IOException {
        controller = null;
    }

    /**
     * Gets all transfers
     * @throws Throwable
     */
    @Test
    public void testTestGetTransfers1() throws Throwable {

        // Set callback and perform API call
        ListTransfers result = null;
        controller.setHttpCallBack(httpResponse);
        try {
            result = controller.getTransfers1();
        } catch(APIException e) {};

       // Test whether the response is null
        assertNotNull("Response is null", 
                httpResponse.getResponse());
        // Test response code
        assertEquals("Status is not 200", 
                200, httpResponse.getResponse().getStatusCode());

        // Test headers
        Map<String, String> headers = new LinkedHashMap<String, String>();
        headers.put("Content-Type", "application/json");
        
        assertTrue("Headers do not match", TestHelper.areHeadersProperSubsetOf(
                headers, httpResponse.getResponse().getHeaders(), true));

    }

}
